### ISSUE TITLE
BrowserStack "localIdentifier" value is not unique enough by default

### ISSUE THREAD

**Issue by raido** [kategengler/ember-cli-browserstack#10]
BrowserStack `localIdentifier` value is taken from here:
https://github.com/kategengler/ember-cli-browserstack/blob/master/lib/utils/build-name-from-env.js

Same value is used for `build` property. Problem is that if you for example run a matrix build on Github Actions or any other CI. You would have N number of parallel runs all having the same `localIdentifier`.

This means that from BrowserStack cloud perspective it has N number of clients all identified as one. Therefore BrowserStack cloud does not know where to route traffic and things just fail.

We can add `process.env.BROWSERTACK_LOCAL_IDENTIFIER` capability to customise this value OR we can just default to using v4 uuid by default. In general `localIdentifier` is technical value overall and really not visible anywhere in BrowserStack UI etc.

**Comment by kategengler** [comment]
The `localIdentifier` is currently passed to both the tunnel start and the browser launch. I remember this being necessary but can find NO documentation of this. 

That said, ember-cli-browserstack certainly works in matrix builds, it has been used that way since the beginning.

**Comment by raido** [comment]
There is some documentation over here: https://www.browserstack.com/local-testing/automate#multiple-local-testing-connections

It can currently work with matrix builds most of time because all browser launch quickly. But let's imagine that some browser takes a bit of time to launch in let's say 5 browser matrix build.

By the time fifth launches and start loading the tests index.html file it can fail in mid request simply because Browserstack routed traffic to wrong local instance, because it had multiple instances with same identifier.

It might be less of problem in the context for testing Ember apps but I just recently faced this when I built a local mock testing server running on express.js and I had random failures because traffic was not routed from Browserstack to correct mock testing server instance because they all had same local identifier.

**Comment by kategengler** [comment]
My guess is that it currently works on CI systems that have a build number env var that is unique per matrix run.

**Comment by raido** [comment]
Yes, in that case it would also work automagically.

**Comment by raido** [comment]
> Note: Not using the --local-identifier flag (for each Local Testing connection) will cut off the existing connection and create a new one.

As said in https://www.browserstack.com/local-testing/automate#multiple-local-testing-connections - we should either have safe default by using v4 uuid or then ability to modify the value via something like `process.env.BROWSERTACK_LOCAL_IDENTIFIER` as I proposed above.

Which way would you prefer? I can open a PR for this.

**Comment by kategengler** [comment]
I think the env var makes sense, it is provided by default by many CI

**Comment by raido** [comment]
I opened a PR to address this using env variable.
