### ISSUE TITLE
How to specify browserstack project

### ISSUE THREAD

**Issue by simonihmig** [kategengler/ember-cli-browserstack#6]
The guide to add a [browserstack badge](https://www.browserstack.com/automate/status-badges) mentions one should specify a `project` capability:

> Note: You can specify a project for a build / session by passing the capability project: <project_name> in your test suite.

Not sure though how I can do that with this addon. Would that have to be specified in the browser definition, and be passed through https://github.com/kategengler/ember-cli-browserstack/blob/master/lib/tasks/launch-browserstack-browser.js, which it does not seem to support? Or do I miss something else?

Apart from that, working quite nicely so far: https://github.com/kaliber5/ember-bootstrap/pull/764
Thanks @kategengler! 👏

**Comment by kategengler** [comment]
Hi! 

My recollection isn't perfect but I recall having problems when I passed in a project and having to explicitly leave it out. If you wanted to try it, that file is the correct place to add the capability and it would be need to be passed as an argument on each browser definition. 

That said, you don't need to specify a project to get a badge. All your builds will be grouped by default under a 'Untitled' project that you'll see if you curl the URL in those badge directions.

**Comment by simonihmig** [comment]
> That said, you don't need to specify a project to get a badge. All your builds will be grouped by default under a 'Untitled' project that you'll see if you curl the URL in those badge directions.

Ok. I thought that would give me a different ID for each build, so nothing I could use for the badge. But I'll try that out! Thank you!

**Comment by raido** [comment]
I'll open PR for this, it would be still nicely we optionally it could be passed. I have 10+ projects on same BrowserStack account and having them grouped by project would be very nice.
